config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
root to: 'posts#index'
resources :users do
  resources :posts
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :content, presence: true
    validates_associated :user
end

app/controllers/api/v1/posts.rb
module Api
    module V1
      class Posts < Grape::API
        include Api::V1::Defaults
  
        resource :posts do
          desc "Return all posts"
          get "", root: :posts do
            Post.all
          end
  
          desc "Return a post"
          params do
            requires :id, type: String, desc: "ID of the 
              post"
          end
          get ":id", root: "graduate" do
            Post.where(id: permitted_params[:id]).first!
          end
        end
      end
    end
  end

app/controllers/post_controller.rb
class PostController < ApplicationController

    def index
      @posts = Post.all
   end

   def mine
      @user = User.find(params[:user_id])
      @posts = @user.posts.all
   end
   
   def show
      @post = Post.find_by(id: params[:id])
      if @post.nil?
         @posts = Post.all
         flash.now[:alert] = "Post was not found"
         render "index"
      end
   end
  
   def new
      @post = Post.new
   end

   def post_params
      params.require(:posts).permit(:content, :user_id, :created_at)
   end

   def create
      @post = Post.new(post_params)

      if @post.save
         redirect_to :action => 'list'
      else
         render :action => 'create'
      end
   end
   
   def edit
      @post = Post.find(params[:id])
   end
   
   def post_param
      params.require(:post).permit(:content, :user_id)
   end
   
   def update
      @post = Post.find(params[:id])
      
      #if @post.update_attributes(post_param)
      if @post.update_attribute(:content,post_param[:content])
         #redirect_to :action => 'show', :id => @post
         #flash[:success] = "Post Updated!"
         redirect_to(@post)
      else
         #render :action => 'edit'
         render "edit"
      end
   end
   
   def destroy
      Post.find(params[:id]).destroy
      redirect_to :action => 'index'
   end
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   before_action :authenticate_user!
   load_and_authorize_resource
   layout "form", only: [:edit, :create, :new]

    def index
      if user_signed_in?
         @posts = Post.all.order(created_at: :desc)
      else
         redirect_to new_user_session_path
      end
   end

   def mine
      @posts = current_user.posts.all
   end
   
   def show
      @post = Post.find_by(id: params[:id])
      if @post.nil?
         @posts = Post.all
         flash.now[:alert] = "Post was not found"
         render "index"
      end
   end
  
   def new
      @post = current_user.posts.new
      @path = user_posts_path(current_user)

   end

   def post_params
      params.require(:post).permit(:content, :user_id, :created_at, :id)
   end

   def create
    
      @post = Post.new(post_params)      
      if @post.save
         PostMailer.with(post: @post).new_post_email.deliver_later
         flash[:notice] = 'Post was successfully created.'
         redirect_to user_posts_path(current_user)
      else
         render :action => 'create'
      end
   end
   
   def edit
      @post = Post.find(params[:id])
      @path = user_post_path(current_user, @post)
   
   end
   
   
   def update
      @post = Post.find(params[:id])
      
      #if @post.update_attributes(post_param)
      if @post.update(post_params.as_json)
         #redirect_to :action => 'show', :id => @post
         #flash[:success] = "Post Updated!"
         redirect_to(user_posts_path(current_user ))
      else
         #render :action => 'edit'
         render "edit"
      end
   end
   
   def destroy
      Post.find(params[:id]).destroy 
      redirect_to :action => 'index'
   end
   
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/edit.html.erb
<% content_for :head do %>
  <title>Edit Post | Coeus Tweetz</title>
<% end %>
<h1>Edit Post</h1>
<%= render "shared/form-post" %>

app/views/post/index.html.erb
<% content_for :head do %>
  <title>All Posts | Coeus Tweetz</title>
<% end %>
<h1>All Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Published at</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= post.content %></td>
        <td><%= distance_of_time_in_words(post.created_at, Time.now, include_seconds: true) %></td>
        <td><%= link_to "Show", post %></td>
        <td><%= link_to "Edit", edit_post_path(post) %></td>
        <td><%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New post", new_post_path %>

app/views/post/show.html.erb
<% content_for :head do %>
  <title>Post | Coeus Tweetz</title>
<% end %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Published at</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @post.user.name %></td>
        <td><%= @post.content %></td>
        <td><%= @post.created_at.localtime.strftime("%d-%m-%Y %H:%M:%S") %></td>
        <td><%= link_to "Edit", edit_post_path(@post) %></td>
        <td><%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
  </tbody>
</table>

<%= link_to "Show All", post_index_path %>