config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
root to: 'posts#index'
resources :users do
  resources :posts
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :content, presence: true
    validates_associated :user
end

app/controllers/api/v1/posts.rb
module Api
    module V1
      class Posts < Grape::API
        include Api::V1::Defaults
  
        resource :posts do
          desc "Return all posts"
          get "", root: :posts do
            Post.all
          end
  
          desc "Return a post"
          params do
            requires :id, type: String, desc: "ID of the 
              post"
          end
          get ":id", root: "graduate" do
            Post.where(id: permitted_params[:id]).first!
          end
        end
      end
    end
  end

app/controllers/post_controller.rb
class PostController < ApplicationController

    def index
      @posts = Post.all
   end

   def mine
      @user = User.find(params[:user_id])
      @posts = @user.posts.all
   end
   
   def show
      @post = Post.find_by(id: params[:id])
      if @post.nil?
         @posts = Post.all
         flash.now[:alert] = "Post was not found"
         render "index"
      end
   end
  
   def new
      @post = Post.new
   end

   def post_params
      params.require(:posts).permit(:content, :user_id, :created_at)
   end

   def create
      @post = Post.new(post_params)

      if @post.save
         redirect_to :action => 'list'
      else
         render :action => 'create'
      end
   end
   
   def edit
      @post = Post.find(params[:id])
   end
   
   def post_param
      params.require(:post).permit(:content, :user_id)
   end
   
   def update
      @post = Post.find(params[:id])
      
      #if @post.update_attributes(post_param)
      if @post.update_attribute(:content,post_param[:content])
         #redirect_to :action => 'show', :id => @post
         #flash[:success] = "Post Updated!"
         redirect_to(@post)
      else
         #render :action => 'edit'
         render "edit"
      end
   end
   
   def destroy
      Post.find(params[:id]).destroy
      redirect_to :action => 'index'
   end
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   before_action :authenticate_user!
   load_and_authorize_resource
   layout "form", only: [:edit, :create, :new]

    def index
      if user_signed_in?
         @posts = Post.all.order(created_at: :desc)
      else
         redirect_to new_user_session_path
      end
   end

   def mine
      @posts = current_user.posts.all
   end
   
   def show
      @post = Post.find_by(id: params[:id])
      if @post.nil?
         @posts = Post.all
         flash.now[:alert] = "Post was not found"
         render "index"
      end
   end
  
   def new
      @post = current_user.posts.new
      @path = user_posts_path(current_user)

   end

   def post_params
      params.require(:post).permit(:content, :user_id, :created_at, :id)
   end

   def create
    
      @post = Post.new(post_params)      
      if @post.save
         PostMailer.with(post: @post).new_post_email.deliver_later
         flash[:notice] = 'Post was successfully created.'
         redirect_to user_posts_path(current_user)
      else
         render :action => 'create'
      end
   end
   
   def edit
      @post = Post.find(params[:id])
      @path = user_post_path(current_user, @post)
   
   end
   
   
   def update
      @post = Post.find(params[:id])
      
      #if @post.update_attributes(post_param)
      if @post.update(post_params.as_json)
         #redirect_to :action => 'show', :id => @post
         #flash[:success] = "Post Updated!"
         redirect_to(user_posts_path(current_user ))
      else
         #render :action => 'edit'
         render "edit"
      end
   end
   
   def destroy
      Post.find(params[:id]).destroy 
      redirect_to :action => 'index'
   end
   
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: @path do |form| %>
  <%= form.text_area :content, size: "50x10", class: "form-control", placeholder: "What's on your mind..." %>
  <%= form.hidden_field :user_id, value: @post.user_id %>
  <br>
  <%= form.submit class: "btn btn-warning" %>
<%= link_to 'Back', 'javascript:history.go(-1);', class: "btn btn-warning"%>
<% end %>
  
  

app/views/posts/edit.html.erb
<% content_for :card_header do %>
Edit Post
<% end %>
<%= render "form" %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
<% content_for :head do %>
  <title>All Posts | Coeus Tweetz</title>
<% end %>


<div class="container">
<h1>All Posts</h1>
<p id="notice"><%= notice %></p>
<%= link_to "New post", new_user_post_path(current_user), class:"btn btn-warning" %><br>
<hr>

<% @posts.each do |post| %>
<div class="card">
  <h6 class="card-header"><b><%= post.user.name.titleize %></b></h6>
    
  <div class="card-body">
    <h6 class="card-title"><%= raw(post.content) %></h6><br><br>
    <div style="float: left; width: auto; margin-right:3px;">
    <%= link_to "Show", user_post_path(current_user, post), class:"btn btn-warning btn-sm" %>

    <% if can? :update, post %>
      <%= link_to "Edit", edit_user_post_path(post.user, post) , class:"btn btn-info btn-sm"%> 
    <%end%>
  </div>
    <% if can? :destroy, post %>
    <%= button_to 'Delete', user_post_path(current_user.id, post.id), method: :delete, class:"btn btn-danger btn-sm" %><br>
    <%end%>
  </div>
  <div class="card-footer text-muted">
    <%= distance_of_time_in_words(post.created_at, Time.now, include_seconds: true) %>
  </div>
</div>
<% end %>

</div>
<br>

<%end%>

app/views/posts/new.html.erb
<% content_for :card_header do %>
New Post
<% end %>
<%= render "form" %>

app/views/posts/show.html.erb
<% content_for :head do %>
  <title>Post | Coeus Tweetz</title>
<% end %>
<div class="container">
<h1>Post</h1>
<br><br>
<div class="card">
  <h6 class="card-header"><b><%= @post.user.name %></b></h6>
    
  <div class="card-body">
    <h6 class="card-title"><%= @post.content %></h6><br><br>
  </div>
  <div class="card-footer text-muted">
    <%= distance_of_time_in_words(@post.created_at, Time.now, include_seconds: true) %>
  </div>
</div>


<div style="float: left; width: auto; margin-right:3px;">
<%= link_to "Back", user_posts_path(current_user), class:"btn btn-warning btn-sm"%>  
<% if can? :update, @post %>
  <%= link_to "Edit", edit_user_post_path(@post.user, @post) , class:"btn btn-info btn-sm"%> 
<%end%>
</div>
<% if can? :destroy, @post %>
  <%= button_to 'Delete', user_post_path(current_user.id, @post.id), method: :delete, class:"btn btn-danger btn-sm" , :confirm => "Are you sure?" %><br>
<%end%>   